// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWcSFilOrcfsXS4FKhuPIonJg0v4QpXs',
    appId: '1:554134551522:web:2ade0d118107d3833c17bb',
    messagingSenderId: '554134551522',
    projectId: 'auth-6b85f',
    authDomain: 'auth-6b85f.firebaseapp.com',
    storageBucket: 'auth-6b85f.firebasestorage.app',
    measurementId: 'G-89076E3PS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FyMqJ2Nh6WBAt2Gv8ZhiEs777zS-d-I',
    appId: '1:554134551522:android:89a8bcce0505aa0d3c17bb',
    messagingSenderId: '554134551522',
    projectId: 'auth-6b85f',
    storageBucket: 'auth-6b85f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIaD4olThjn5AgInOHVMn5ZFHmsKkR3dA',
    appId: '1:554134551522:ios:68a12333010b63683c17bb',
    messagingSenderId: '554134551522',
    projectId: 'auth-6b85f',
    storageBucket: 'auth-6b85f.firebasestorage.app',
    iosBundleId: 'com.example.fireAuth',
  );
}
